#if defined(CLIENT_DLL)
// No client-side highlight-context code. The S21 client binds these natives itself and
// the SDK registration path that reached this half no longer exists.

#else // !CLIENT_DLL
//=============================================================================//
//
// Purpose: SDK name-to-id highlight context registry. Virtual ids >7 remap to slot 7.
//
//=============================================================================//

#include "core/stdafx.h"
#include "tier1/convar.h"
#include "vscript/languages/squirrel_re/include/sqvm.h"
#include "vscript/languages/squirrel_re/vsquirrel.h"
#include "vscript/languages/squirrel_re/include/squirrel.h"
#include "game/shared/vscript_gamedll_defs.h"
#include "game/shared/sdk_entity_state.h"
#include "highlight_context.h"

#include <unordered_map>
#include <string>
#include <cstring>

// CLIENT entity highlight field offsets. SERVER uses +288 / +480 / +536 —
// writing to the wrong set silently corrupts adjacent memory.
static constexpr int HIGHLIGHT_REMAP_PHYSICAL_SLOT = 7;
static constexpr int CLIENT_ENT_HIGHLIGHT_PARAMS_BASE       = 440;
static constexpr int CLIENT_ENT_HIGHLIGHT_FUNCTIONBITS_BASE = 632;
static constexpr int CLIENT_ENT_HIGHLIGHT_CONTEXT_ID        = 784;

//-----------------------------------------------------------------------------
// Highlight context data
//-----------------------------------------------------------------------------
static constexpr int MAX_HIGHLIGHT_CONTEXTS = 256;
static constexpr int MAX_HIGHLIGHT_PARAMS = 4;
static constexpr int INVALID_HIGHLIGHT_ID = 255;

struct HighlightContextData_t
{
	char name[64] = {};
	int insideFunction = 0;
	int insideFunctionFocused = 0;
	int outsideFunction = 0;
	int outsideFunctionFocused = 0;
	float outlineRadius = 0.0f;
	float params[MAX_HIGHLIGHT_PARAMS][3] = {};
	int drawFunc = 0;
	int flags = 0;
	float nearFadeDistance = 0.0f;
	float farFadeDistance = 0.0f;
	float focusedColor[3] = {};
	bool isAfterPostProcess = false;
	bool isEntityVisible = true;
	bool adsFade = true;
	int colorID = 0;
	bool registered = false;
};

// Generated by tools/gen_highlight_defaults.py; copied into s_contexts on
// first GetId(name) lookup.
struct HighlightDefault_t
{
	const char* name;
	int insideSlot;
	int insideSlotFocused;
	int outsideSlot;
	int outsideSlotFocused;
	float param0[3];
	float param1[3];
	float outlineRadius;
	int drawFunc;
	bool entityVisible;
	bool afterPostProcess;
	bool adsFade;
	float nearFadeDistance;
	float farFadeDistance;
	int colorID;
};

#include "highlight_defaults.inl"

// S21 HighlightContext_GetId returns hcxt load order (in-game, client_only
// deferred). First-GetId order does not match that table; id 0 is
// vehicle_enemy_los_highlight (enemy orange).
static const char* const kS21HighlightIds[] = {
	"vehicle_enemy_los_highlight",
	"pure_observer_highlight",
	"caustic_gas_canister",
	"dropship_friendly",
	"survival_item_rare_no_los_check",
	"shadow_friendly",
	"enemy_los_highlight",
	"enemy_ai",
	"survival",
	"survival_item_weapon",
	"hover_vehicle_highlight",
	"sp_objective_entity",
	"castle_wall_focus",
	"sp_interact_object",
	"killer_outline",
	"survival_item_legendary",
	"crypto_camera_friendly",
	"survival_item_legendary_longerHighlightDist",
	"dev_emote_hostile",
	"firingrange_supplybox",
	"survival_item_gh_longerHighlightDist",
	"test",
	"sp_objective_outline",
	"survival_item_gh",
	"vehicle_friendly_los_highlight",
	"revealed_friendly",
	"sp_friendly_hero",
	"revenant_assassins_instinct_passive",
	"enemy_player_decoy",
	"survival_item_legendary_no_los_check",
	"sp_friendly_hero_force_on",
	"friendly_ai",
	"enemy_sonar",
	"sp_friendly_pilot",
	"survival_item_common_no_los_check",
	"survival_item_epic_longerHighlightDist",
	"void_vision_self",
	"nova_blackhole_threat",
	"survival_item_common_longerHighlightDist",
	"armored_leap_threat",
	"survival_item_heirloom",
	"bloodhound_sonar_blockscan",
	"decoy_prop",
	"dropship_enemy",
	"survival_friendly_skydiving",
	"survival_item_epic",
	"void_vision_structure",
	"bloodhound_sonar",
	"survival_item_gh_no_los_check",
	"friendly_player_decoy",
	"survival_item_epic_no_los_check",
	"survival_item_rare_longerHighlightDist",
	"survival_item_rare",
	"dev_emote_friendly",
	"ability_reveal",
	"survival_item_ammo_a",
	"nova_blackhole_newt",
	"caustic_gas_threat",
	"thermal_denial_ghost",
	"staging_gun_range_target_appear",
	"survival_item_heirloom_no_los_check",
	"rev_army_enemy",
	"ability_reveal_blockscan",
	"survival_item_common",
	"enemy_nightmap",
	"smoke_highlight_blockscan",
	"survival_item_heirloom_longerHighlightDist",
	"survival_enemy_skydiving",
	"spot_view_model",
	"sonar_player_clone",
	"sonar_view_model",
	"firing_range_supply_box",
	"deployable_model_invalid",
	"haunt_trap_view_model",
	"deployable_model",
	"menu_scene",
	"menu_model_in_match",
	"mythic_model_fade",
	"flash_menu_model",
	"deployable_model_newcastle",
	"ping_view_model",
};
static constexpr int kS21HighlightIdCount =
	static_cast<int>(sizeof(kS21HighlightIds) / sizeof(kS21HighlightIds[0]));

static HighlightContextData_t s_contexts[MAX_HIGHLIGHT_CONTEXTS];
static std::unordered_map<std::string, int> s_nameToId;
static int s_nextId = 0;
static bool s_s21IdsReady = false;

static const HighlightDefault_t* FindDefault(const char* name)
{
	for (size_t i = 0; i < kHighlightDefaultsCount; ++i)
	{
		if (strcmp(kHighlightDefaults[i].name, name) == 0)
			return &kHighlightDefaults[i];
	}
	return nullptr;
}

// Per-entity virtual ctxId activated via SetCurrentContext. Lets
// GetCurrentContext return the virtual id instead of the raw physical slot.
static SDKEntityMap<int> s_entityActiveVirtualContext(ESide::Client, "highlightVirtualCtx");

// Per-entity binding of generic type (NEUTRAL/FRIENDLY/ENEMY/OWNED = 0..3)
// to virtual ctxId, populated by Highlight_SetGenericHighlightContext.
struct EntityGenericHighlightState_t
{
	int ctxIdBySlot[4] = { -1, -1, -1, -1 };
};
static SDKEntityMap<EntityGenericHighlightState_t> s_entityGenericCtx(ESide::Client, "highlightGenericCtx");

static void ApplyHighlightDefault(HighlightContextData_t& ctx, const char* name)
{
	const HighlightDefault_t* def = FindDefault(name);
	if (!def)
		return;
	ctx.insideFunction          = def->insideSlot;
	ctx.insideFunctionFocused   = def->insideSlotFocused;
	ctx.outsideFunction         = def->outsideSlot;
	ctx.outsideFunctionFocused  = def->outsideSlotFocused;
	ctx.outlineRadius           = def->outlineRadius;
	ctx.drawFunc                = def->drawFunc;
	ctx.isEntityVisible         = def->entityVisible;
	ctx.isAfterPostProcess      = def->afterPostProcess;
	ctx.adsFade                 = def->adsFade;
	ctx.nearFadeDistance        = def->nearFadeDistance;
	ctx.farFadeDistance         = def->farFadeDistance;
	ctx.colorID                 = def->colorID;
	for (int k = 0; k < 3; ++k) ctx.params[0][k] = def->param0[k];
	for (int k = 0; k < 3; ++k) ctx.params[1][k] = def->param1[k];
}

static void EnsureS21HighlightIds(void)
{
	if (s_s21IdsReady)
		return;
	s_s21IdsReady = true;

	for (int id = 0; id < kS21HighlightIdCount; ++id)
	{
		const char* name = kS21HighlightIds[id];
		if (!name || !*name)
			continue;
		if (s_nameToId.find(name) != s_nameToId.end())
			continue;
		if (id >= MAX_HIGHLIGHT_CONTEXTS)
			break;

		HighlightContextData_t& ctx = s_contexts[id];
		strncpy(ctx.name, name, sizeof(ctx.name) - 1);
		ctx.registered = true;
		ApplyHighlightDefault(ctx, name);
		s_nameToId[name] = id;
	}

	if (s_nextId < kS21HighlightIdCount)
		s_nextId = kS21HighlightIdCount;

	Msg(eDLL_T::SERVER, "[HL-ID] baked %d S21 hcxt ids (id0='%s')\n",
		kS21HighlightIdCount, kS21HighlightIds[0]);
}

static int FindOrCreateContext(const char* name)
{
	if (!name || !*name)
		return INVALID_HIGHLIGHT_ID;

	EnsureS21HighlightIds();

	auto it = s_nameToId.find(name);
	if (it != s_nameToId.end())
		return it->second;

	if (s_nextId >= MAX_HIGHLIGHT_CONTEXTS)
		return INVALID_HIGHLIGHT_ID;

	int id = s_nextId++;
	HighlightContextData_t& ctx = s_contexts[id];
	strncpy(ctx.name, name, sizeof(ctx.name) - 1);
	ctx.registered = true;
	ApplyHighlightDefault(ctx, name);

	s_nameToId[name] = id;
	return id;
}

static bool IsValidContext(int id)
{
	return id >= 0 && id < MAX_HIGHLIGHT_CONTEXTS && s_contexts[id].registered;
}

static bool IsVirtualContext(int id)
{
	return id > 7 && id < MAX_HIGHLIGHT_CONTEXTS;
}

// Flip the highlight-dirty bit the client SetFunctions skips, and register
// into the slab at +0x2C38 or Highlight_SetVisibilityType silently no-ops.
static void MarkClientEntityHighlightDirty(void* entity)
{
	if (!g_pHighlightSystem || !*g_pHighlightSystem || !entity)
		return;

	const uintptr_t entAddr = reinterpret_cast<uintptr_t>(entity);
	const uint16_t handle = *reinterpret_cast<const uint16_t*>(entAddr + 88);
	if (handle == 0xFFFF)
		return;

	uint8_t* const systemBase = static_cast<uint8_t*>(*g_pHighlightSystem);
	uint8_t* const tableBase = *reinterpret_cast<uint8_t**>(systemBase + 120);
	if (!tableBase)
		return;

	volatile short* const slot = reinterpret_cast<volatile short*>(tableBase + 2 * handle + 64);
	_InterlockedOr16(slot, 0x200);

	// is idempotent via entity[+1857]==0 guard.
	if (v_ClientEnt_Highlight_RegisterWithSystem
	 && g_pHighlightEntitySlab)
	{
		const uint16_t slotIdx = *reinterpret_cast<const uint16_t*>(entAddr + 1858);
		if (slotIdx != 0xFFFF && slotIdx != 0xFFFD)
		{
			void* const slabEntPtr = *reinterpret_cast<void* const*>(
				g_pHighlightEntitySlab + 0x2C38 + 16 * slotIdx);
			const uint8_t registered = *reinterpret_cast<const uint8_t*>(entAddr + 1857);
			if (!slabEntPtr && registered == 0)
				v_ClientEnt_Highlight_RegisterWithSystem(entity, 0);
		}
	}
}

// SetCurrentContext early-outs when target==current. Bounce via -1 so
// funcBits that changed while the slot was already active get re-applied.
static void ForceClientEntitySetCurrentContext(void* entity, int targetSlot)
{
	const uintptr_t entAddr = reinterpret_cast<uintptr_t>(entity);
	const int currentCtx = *reinterpret_cast<int*>(entAddr + CLIENT_ENT_HIGHLIGHT_CONTEXT_ID);

	if (currentCtx == targetSlot)
		v_ClientEnt_Highlight_SetCurrentContext(entity, -1);

	v_ClientEnt_Highlight_SetCurrentContext(entity, targetSlot);
	MarkClientEntityHighlightDirty(entity);
}

// Apply named-context config to a physical slot via engine natives. Must
// route through SetFunctions/SetParam — raw packing mis-bits byte3
// (drawFunc vs highlightId) and the render shader reads the wrong config.
static void WriteContextToClientEntitySlot(void* entity, int physicalSlot, int virtualId)
{
	if (virtualId < 0 || virtualId >= MAX_HIGHLIGHT_CONTEXTS || !s_contexts[virtualId].registered)
		return;
	if (physicalSlot < 0 || physicalSlot > 7)
		return;

	const HighlightContextData_t& ctx = s_contexts[virtualId];

	if (v_ClientEnt_Highlight_SetFunctions)
	{
		v_ClientEnt_Highlight_SetFunctions(
			entity,
			physicalSlot,
			ctx.insideFunction,
			ctx.isEntityVisible,
			ctx.outsideFunction,
			ctx.outlineRadius,
			virtualId,
			ctx.isAfterPostProcess);
	}

	if (v_ClientEnt_Highlight_SetParam)
	{
		float p0[3] = { ctx.params[0][0], ctx.params[0][1], ctx.params[0][2] };
		float p1[3] = { ctx.params[1][0], ctx.params[1][1], ctx.params[1][2] };
		v_ClientEnt_Highlight_SetParam(entity, physicalSlot, 0, p0);
		v_ClientEnt_Highlight_SetParam(entity, physicalSlot, 1, p1);
	}

	MarkClientEntityHighlightDirty(entity);
}

SQRESULT Script_HighlightContext_GetId(HSQUIRRELVM v)
{
	const SQChar* name = nullptr;
	if (SQ_FAILED(sq_getstring(v, 2, &name)) || !name)
		return SQ_ERROR;

	int id = FindOrCreateContext(name);

	sq_pushinteger(v, id);
	SCRIPT_CHECK_AND_RETURN(v, SQ_OK);
}

SQRESULT Script_HighlightContext_SetParam(HSQUIRRELVM v)
{
	SQInteger contextId, paramIdx;
	sq_getinteger(v, 2, &contextId);
	sq_getinteger(v, 3, &paramIdx);

	const SQVector3D* vec = nullptr;
	sq_getvector(v, 4, &vec);

	if (IsValidContext(static_cast<int>(contextId)) && paramIdx >= 0 && paramIdx < MAX_HIGHLIGHT_PARAMS && vec)
	{
		s_contexts[contextId].params[paramIdx][0] = vec->x;
		s_contexts[contextId].params[paramIdx][1] = vec->y;
		s_contexts[contextId].params[paramIdx][2] = vec->z;
	}

	SCRIPT_CHECK_AND_RETURN(v, SQ_OK);
}

SQRESULT Script_HighlightContext_GetParam(HSQUIRRELVM v)
{
	SQInteger contextId, paramIdx;
	sq_getinteger(v, 2, &contextId);
	sq_getinteger(v, 3, &paramIdx);

	float x = 0.0f, y = 0.0f, z = 0.0f;
	if (IsValidContext(static_cast<int>(contextId)) && paramIdx >= 0 && paramIdx < MAX_HIGHLIGHT_PARAMS)
	{
		x = s_contexts[contextId].params[paramIdx][0];
		y = s_contexts[contextId].params[paramIdx][1];
		z = s_contexts[contextId].params[paramIdx][2];
	}

	SQVector3D result_vec(x, y, z);
	sq_pushvector(v, &result_vec);
	SCRIPT_CHECK_AND_RETURN(v, SQ_OK);
}

SQRESULT Script_HighlightContext_SetDrawFunc(HSQUIRRELVM v)
{
	SQInteger contextId, drawFunc;
	sq_getinteger(v, 2, &contextId);
	sq_getinteger(v, 3, &drawFunc);

	if (IsValidContext(static_cast<int>(contextId)))
		s_contexts[contextId].drawFunc = static_cast<int>(drawFunc);

	SCRIPT_CHECK_AND_RETURN(v, SQ_OK);
}

SQRESULT Script_HighlightContext_GetDrawFunc(HSQUIRRELVM v)
{
	SQInteger contextId;
	sq_getinteger(v, 2, &contextId);

	int result = 0;
	if (IsValidContext(static_cast<int>(contextId)))
		result = s_contexts[contextId].drawFunc;

	sq_pushinteger(v, result);
	SCRIPT_CHECK_AND_RETURN(v, SQ_OK);
}

SQRESULT Script_HighlightContext_SetRadius(HSQUIRRELVM v)
{
	SQInteger contextId;
	SQFloat radius;
	sq_getinteger(v, 2, &contextId);
	sq_getfloat(v, 3, &radius);

	if (IsValidContext(static_cast<int>(contextId)))
		s_contexts[contextId].outlineRadius = static_cast<float>(radius);

	SCRIPT_CHECK_AND_RETURN(v, SQ_OK);
}

SQRESULT Script_HighlightContext_GetOutlineRadius(HSQUIRRELVM v)
{
	SQInteger contextId;
	sq_getinteger(v, 2, &contextId);

	float result = 0.0f;
	if (IsValidContext(static_cast<int>(contextId)))
		result = s_contexts[contextId].outlineRadius;

	sq_pushfloat(v, result);
	SCRIPT_CHECK_AND_RETURN(v, SQ_OK);
}

SQRESULT Script_HighlightContext_GetInsideFunction(HSQUIRRELVM v)
{
	SQInteger contextId;
	sq_getinteger(v, 2, &contextId);

	int result = 0;
	if (IsValidContext(static_cast<int>(contextId)))
		result = s_contexts[contextId].insideFunction;

	sq_pushinteger(v, result);
	SCRIPT_CHECK_AND_RETURN(v, SQ_OK);
}

SQRESULT Script_HighlightContext_GetOutlineFunction(HSQUIRRELVM v)
{
	SQInteger contextId;
	sq_getinteger(v, 2, &contextId);

	int result = 0;
	if (IsValidContext(static_cast<int>(contextId)))
		result = s_contexts[contextId].outsideFunction;

	sq_pushinteger(v, result);
	SCRIPT_CHECK_AND_RETURN(v, SQ_OK);
}

SQRESULT Script_HighlightContext_SetFlags(HSQUIRRELVM v)
{
	SQInteger contextId, flags;
	sq_getinteger(v, 2, &contextId);
	sq_getinteger(v, 3, &flags);

	if (IsValidContext(static_cast<int>(contextId)))
		s_contexts[contextId].flags = static_cast<int>(flags);

	SCRIPT_CHECK_AND_RETURN(v, SQ_OK);
}

SQRESULT Script_HighlightContext_SetFill(HSQUIRRELVM v)
{
	SQInteger contextId, fn;
	sq_getinteger(v, 2, &contextId);
	sq_getinteger(v, 3, &fn);

	if (IsValidContext(static_cast<int>(contextId)))
		s_contexts[contextId].insideFunction = static_cast<int>(fn);

	SCRIPT_CHECK_AND_RETURN(v, SQ_OK);
}

SQRESULT Script_HighlightContext_SetOutline(HSQUIRRELVM v)
{
	SQInteger contextId, fn;
	sq_getinteger(v, 2, &contextId);
	sq_getinteger(v, 3, &fn);

	if (IsValidContext(static_cast<int>(contextId)))
		s_contexts[contextId].outsideFunction = static_cast<int>(fn);

	SCRIPT_CHECK_AND_RETURN(v, SQ_OK);
}

SQRESULT Script_HighlightContext_SetFillFocused(HSQUIRRELVM v)
{
	SQInteger contextId, fn;
	sq_getinteger(v, 2, &contextId);
	sq_getinteger(v, 3, &fn);

	if (IsValidContext(static_cast<int>(contextId)))
		s_contexts[contextId].insideFunctionFocused = static_cast<int>(fn);

	SCRIPT_CHECK_AND_RETURN(v, SQ_OK);
}

SQRESULT Script_HighlightContext_SetOutlineFocused(HSQUIRRELVM v)
{
	SQInteger contextId, fn;
	sq_getinteger(v, 2, &contextId);
	sq_getinteger(v, 3, &fn);

	if (IsValidContext(static_cast<int>(contextId)))
		s_contexts[contextId].outsideFunctionFocused = static_cast<int>(fn);

	SCRIPT_CHECK_AND_RETURN(v, SQ_OK);
}

SQRESULT Script_HighlightContext_SetADSFade(HSQUIRRELVM v)
{
	SQInteger contextId; SQBool val;
	sq_getinteger(v, 2, &contextId);
	sq_getbool(v, 3, &val);

	if (IsValidContext(static_cast<int>(contextId)))
		s_contexts[contextId].adsFade = val != 0;

	SCRIPT_CHECK_AND_RETURN(v, SQ_OK);
}

SQRESULT Script_HighlightContext_SetAfterPostProcess(HSQUIRRELVM v)
{
	SQInteger contextId; SQBool val;
	sq_getinteger(v, 2, &contextId);
	sq_getbool(v, 3, &val);

	if (IsValidContext(static_cast<int>(contextId)))
		s_contexts[contextId].isAfterPostProcess = val != 0;

	SCRIPT_CHECK_AND_RETURN(v, SQ_OK);
}

SQRESULT Script_HighlightContext_SetEntityVisible(HSQUIRRELVM v)
{
	SQInteger contextId; SQBool val;
	sq_getinteger(v, 2, &contextId);
	sq_getbool(v, 3, &val);

	if (IsValidContext(static_cast<int>(contextId)))
		s_contexts[contextId].isEntityVisible = val != 0;

	SCRIPT_CHECK_AND_RETURN(v, SQ_OK);
}

SQRESULT Script_HighlightContext_SetDisableDeathFade(HSQUIRRELVM v)
{
	SQInteger contextId; SQBool val;
	sq_getinteger(v, 2, &contextId);
	sq_getbool(v, 3, &val);

	if (IsValidContext(static_cast<int>(contextId)))
	{
		if (val) s_contexts[contextId].flags |= 0x1;
		else     s_contexts[contextId].flags &= ~0x1;
	}

	SCRIPT_CHECK_AND_RETURN(v, SQ_OK);
}

SQRESULT Script_HighlightContext_SetNearFadeDistance(HSQUIRRELVM v)
{
	SQInteger contextId;
	SQFloat dist;
	sq_getinteger(v, 2, &contextId);
	sq_getfloat(v, 3, &dist);

	if (IsValidContext(static_cast<int>(contextId)))
		s_contexts[contextId].nearFadeDistance = static_cast<float>(dist);

	SCRIPT_CHECK_AND_RETURN(v, SQ_OK);
}

SQRESULT Script_HighlightContext_SetFarFadeDistance(HSQUIRRELVM v)
{
	SQInteger contextId;
	SQFloat dist;
	sq_getinteger(v, 2, &contextId);
	sq_getfloat(v, 3, &dist);

	if (IsValidContext(static_cast<int>(contextId)))
		s_contexts[contextId].farFadeDistance = static_cast<float>(dist);

	SCRIPT_CHECK_AND_RETURN(v, SQ_OK);
}

SQRESULT Script_HighlightContext_SetFocusedColor(HSQUIRRELVM v)
{
	SQInteger contextId;
	sq_getinteger(v, 2, &contextId);

	const SQVector3D* color = nullptr;
	sq_getvector(v, 3, &color);

	if (IsValidContext(static_cast<int>(contextId)) && color)
	{
		s_contexts[contextId].focusedColor[0] = color->x;
		s_contexts[contextId].focusedColor[1] = color->y;
		s_contexts[contextId].focusedColor[2] = color->z;
	}

	SCRIPT_CHECK_AND_RETURN(v, SQ_OK);
}

SQRESULT Script_HighlightContext_IsEntityVisible(HSQUIRRELVM v)
{
	SQInteger contextId;
	sq_getinteger(v, 2, &contextId);

	bool result = true;
	if (IsValidContext(static_cast<int>(contextId)))
		result = s_contexts[contextId].isEntityVisible;

	sq_pushbool(v, result);
	SCRIPT_CHECK_AND_RETURN(v, SQ_OK);
}

SQRESULT Script_HighlightContext_IsAfterPostProcess(HSQUIRRELVM v)
{
	SQInteger contextId;
	sq_getinteger(v, 2, &contextId);

	bool result = false;
	if (IsValidContext(static_cast<int>(contextId)))
		result = s_contexts[contextId].isAfterPostProcess;

	sq_pushbool(v, result);
	SCRIPT_CHECK_AND_RETURN(v, SQ_OK);
}

void HighlightContext_RegisterDrawFuncEnum(HSQUIRRELVM v)
{
	static const char* s_drawFuncNames[] = {
		"ALWAYS",
		"OCCLUDED",
		"LOS",
		"LOS_LINE",
		"LOS_LINE_FADE",
		"LOS_LINE_LONGFADE",
		"REVENANT_ASSASSINS_INSTINCT",
		"LOS_LINE_ENTSONLY_BLOCKSCAN",
		"ENT_APPEAR_EFFECT",
		"LOS_LINE_ENTSONLYCONTENTSBLOCK",
		"CAUSTIC_THREAT",
		"SONAR_DETECTED",
		"SPOT",
		"ALWAYS_LONG_FADE",
		"PICKUP",
		"FORCE_ON",
		"ABILITY_REVEAL",
		"ALLIANCE_PROXIMITY",
	};
	static constexpr int NUM_DRAW_FUNCS = sizeof(s_drawFuncNames) / sizeof(s_drawFuncNames[0]);

	sq_startconsttable(v);
	sq_pushstring(v, "eHighlightDrawFunc", -1);
	sq_newtable(v);

	for (int i = 0; i < NUM_DRAW_FUNCS; i++)
	{
		sq_pushstring(v, s_drawFuncNames[i], -1);
		sq_pushinteger(v, i);
		sq_newslot(v, -3);
	}

	sq_pushstring(v, "LAST_DRAW_FUNC", -1);
	sq_pushinteger(v, NUM_DRAW_FUNCS);
	sq_newslot(v, -3);

	sq_newslot(v, -3);
	sq_endconsttable(v);
}

//=============================================================================
// Entity method overrides. Physical ids 0..7 forward; virtual ids >7 remap.
//=============================================================================

static SQRESULT Script_Entity_Highlight_SetCurrentContext(HSQUIRRELVM v)
{
	void* pEntity = nullptr;
	if (!v_sq_getentity(v, reinterpret_cast<SQEntity*>(&pEntity)))
		return SQ_ERROR;

	SQInteger contextId;
	sq_getinteger(v, 2, &contextId);

	if (!pEntity)
		SCRIPT_CHECK_AND_RETURN(v, SQ_OK);

	int id = static_cast<int>(contextId);

	if (IsVirtualContext(id))
	{
		int boundSlot = -1;
		if (EntityGenericHighlightState_t* state = s_entityGenericCtx.Find(pEntity))
		{
			for (int i = 0; i < 4; ++i)
			{
				if (state->ctxIdBySlot[i] == id)
				{
					boundSlot = i;
					break;
				}
			}
		}

		// Only bounce when the virtual ctxId transitions; repeated calls with
		// the same id would restart the fade animation every tick.
		int* prevVirtual = s_entityActiveVirtualContext.Find(pEntity);
		const bool virtualChanged = !prevVirtual || *prevVirtual != id;
		s_entityActiveVirtualContext[pEntity] = id;

		if (boundSlot >= 0)
		{
			if (virtualChanged)
				ForceClientEntitySetCurrentContext(pEntity, boundSlot);
			else
				v_ClientEnt_Highlight_SetCurrentContext(pEntity, boundSlot);
		}
		else
		{
			if (virtualChanged)
			{
				WriteContextToClientEntitySlot(pEntity, HIGHLIGHT_REMAP_PHYSICAL_SLOT, id);
				ForceClientEntitySetCurrentContext(pEntity, HIGHLIGHT_REMAP_PHYSICAL_SLOT);
			}
			else
			{
				v_ClientEnt_Highlight_SetCurrentContext(pEntity, HIGHLIGHT_REMAP_PHYSICAL_SLOT);
			}
		}
	}
	else
	{
		int* prevVirtual = s_entityActiveVirtualContext.Find(pEntity);
		const bool idChanged = !prevVirtual || *prevVirtual != id;
		if (id == -1)
			s_entityActiveVirtualContext.Erase(pEntity);
		else
			s_entityActiveVirtualContext[pEntity] = id;

		if (idChanged)
			ForceClientEntitySetCurrentContext(pEntity, id);
		else
			v_ClientEnt_Highlight_SetCurrentContext(pEntity, id);
	}

	SCRIPT_CHECK_AND_RETURN(v, SQ_OK);
}

// Returns the bound virtual ctxId (via s_entityGenericCtx or
// s_entityActiveVirtualContext) so script equality checks against their
// original HighlightContext_GetId result match.
static SQRESULT Script_Entity_Highlight_GetCurrentContext(HSQUIRRELVM v)
{
	void* pEntity = nullptr;
	if (!v_sq_getentity(v, reinterpret_cast<SQEntity*>(&pEntity)))
		return SQ_ERROR;

	int result = -1;
	if (pEntity)
	{
		uintptr_t ent = reinterpret_cast<uintptr_t>(pEntity);
		int physicalCtx = *reinterpret_cast<int*>(ent + CLIENT_ENT_HIGHLIGHT_CONTEXT_ID);

		if (physicalCtx == HIGHLIGHT_REMAP_PHYSICAL_SLOT)
		{
			int* pVirtualId = s_entityActiveVirtualContext.Find(pEntity);
			result = pVirtualId ? *pVirtualId : physicalCtx;
		}
		else if (physicalCtx >= 0 && physicalCtx < 4)
		{
			if (EntityGenericHighlightState_t* state = s_entityGenericCtx.Find(pEntity))
			{
				int bound = state->ctxIdBySlot[physicalCtx];
				result = (bound >= 0) ? bound : physicalCtx;
			}
			else
			{
				result = physicalCtx;
			}
		}
		else
		{
			result = physicalCtx;
		}
	}

	sq_pushinteger(v, result);
	SCRIPT_CHECK_AND_RETURN(v, SQ_OK);
}

static SQRESULT Script_Entity_Highlight_SetParam(HSQUIRRELVM v)
{
	void* pEntity = nullptr;
	if (!v_sq_getentity(v, reinterpret_cast<SQEntity*>(&pEntity)))
		return SQ_ERROR;

	SQInteger contextId, paramIdx;
	sq_getinteger(v, 2, &contextId);
	sq_getinteger(v, 3, &paramIdx);

	const SQVector3D* vec = nullptr;
	sq_getvector(v, 4, &vec);

	if (!pEntity || !vec || paramIdx < 0 || paramIdx > 1)
		SCRIPT_CHECK_AND_RETURN(v, SQ_OK);

	int id = static_cast<int>(contextId);

	if (IsVirtualContext(id))
	{
		if (IsValidContext(id))
		{
			s_contexts[id].params[paramIdx][0] = vec->x;
			s_contexts[id].params[paramIdx][1] = vec->y;
			s_contexts[id].params[paramIdx][2] = vec->z;
		}

		float vecData[3] = { vec->x, vec->y, vec->z };
		v_ClientEnt_Highlight_SetParam(pEntity, HIGHLIGHT_REMAP_PHYSICAL_SLOT,
			static_cast<int>(paramIdx), vecData);
	}
	else if (id >= 0 && id <= 7)
	{
		float vecData[3] = { vec->x, vec->y, vec->z };
		v_ClientEnt_Highlight_SetParam(pEntity, id,
			static_cast<int>(paramIdx), vecData);
	}

	SCRIPT_CHECK_AND_RETURN(v, SQ_OK);
}

//-----------------------------------------------------------------------------
// Binds a named context to generic-type slots 0..3 (physical slots 0..3).
//-----------------------------------------------------------------------------
static SQRESULT Script_Entity_Highlight_SetGenericHighlightContext(HSQUIRRELVM v)
{
	void* pEntity = nullptr;
	if (!v_sq_getentity(v, reinterpret_cast<SQEntity*>(&pEntity)))
		return SQ_ERROR;

	SQInteger genericType, contextId;
	SQBool isFocused;
	sq_getinteger(v, 2, &genericType);
	sq_getinteger(v, 3, &contextId);
	sq_getbool(v, 4, &isFocused);

	if (!pEntity)
		SCRIPT_CHECK_AND_RETURN(v, SQ_OK);

	int type = static_cast<int>(genericType);
	int ctxId = static_cast<int>(contextId);

	if (type < 0 || type > 7)
		SCRIPT_CHECK_AND_RETURN(v, SQ_OK);

	EntityGenericHighlightState_t& state = s_entityGenericCtx[pEntity];

	if (!IsValidContext(ctxId))
	{
		if (type < 4)
			state.ctxIdBySlot[type] = -1;
		if (v_ClientEnt_Highlight_SetFunctions)
		{
			v_ClientEnt_Highlight_SetFunctions(pEntity, type, 0, true, 0, 0.0f, 0, false);
			MarkClientEntityHighlightDirty(pEntity);
		}
		SCRIPT_CHECK_AND_RETURN(v, SQ_OK);
	}

	const HighlightContextData_t& ctx = s_contexts[ctxId];
	int insideFn  = isFocused && ctx.insideFunctionFocused  ? ctx.insideFunctionFocused  : ctx.insideFunction;
	int outsideFn = isFocused && ctx.outsideFunctionFocused ? ctx.outsideFunctionFocused : ctx.outsideFunction;

	if (type < 4)
		state.ctxIdBySlot[type] = ctxId;

	if (v_ClientEnt_Highlight_SetFunctions)
	{
		v_ClientEnt_Highlight_SetFunctions(
			pEntity, type,
			insideFn, ctx.isEntityVisible, outsideFn,
			ctx.outlineRadius, ctxId,
			ctx.isAfterPostProcess);
	}

	if (v_ClientEnt_Highlight_SetParam)
	{
		float p0[3] = { ctx.params[0][0], ctx.params[0][1], ctx.params[0][2] };
		float p1[3] = { ctx.params[1][0], ctx.params[1][1], ctx.params[1][2] };
		v_ClientEnt_Highlight_SetParam(pEntity, type, 0, p0);
		v_ClientEnt_Highlight_SetParam(pEntity, type, 1, p1);
	}

	MarkClientEntityHighlightDirty(pEntity);

	SCRIPT_CHECK_AND_RETURN(v, SQ_OK);
}

static SQRESULT Script_Entity_Highlight_GetGenericHighlightContext(HSQUIRRELVM v)
{
	void* pEntity = nullptr;
	if (!v_sq_getentity(v, reinterpret_cast<SQEntity*>(&pEntity)))
		return SQ_ERROR;

	SQInteger genericType;
	sq_getinteger(v, 2, &genericType);

	int result = -1;
	int type = static_cast<int>(genericType);
	if (pEntity && type >= 0 && type < 4)
	{
		EntityGenericHighlightState_t* state = s_entityGenericCtx.Find(pEntity);
		if (state)
			result = state->ctxIdBySlot[type];
	}

	sq_pushinteger(v, result);
	SCRIPT_CHECK_AND_RETURN(v, SQ_OK);
}

static SQRESULT Script_Entity_Highlight_OverrideParam(HSQUIRRELVM v)
{
	void* pEntity = nullptr;
	if (!v_sq_getentity(v, reinterpret_cast<SQEntity*>(&pEntity)))
		return SQ_ERROR;

	SQInteger paramIdx;
	sq_getinteger(v, 2, &paramIdx);

	const SQVector3D* vec = nullptr;
	sq_getvector(v, 3, &vec);

	if (!pEntity || !vec || paramIdx < 0 || paramIdx > 1)
		SCRIPT_CHECK_AND_RETURN(v, SQ_OK);

	int currentCtx = *reinterpret_cast<int*>(
		reinterpret_cast<uintptr_t>(pEntity) + CLIENT_ENT_HIGHLIGHT_CONTEXT_ID);

	if (currentCtx >= 0 && currentCtx <= 7 && v_ClientEnt_Highlight_SetParam)
	{
		float vecData[3] = { vec->x, vec->y, vec->z };
		v_ClientEnt_Highlight_SetParam(pEntity, currentCtx, static_cast<int>(paramIdx), vecData);
	}

	SCRIPT_CHECK_AND_RETURN(v, SQ_OK);
}

// Registers AddFunction entries under the same names as engine entity
// methods so scripts call our wrappers instead of the natives.
void HighlightContext_RegisterEntityOverrides(ScriptClassDescriptor_t* entityStruct)
{
	if (!v_ClientEnt_Highlight_SetCurrentContext)
	{
		Warning(eDLL_T::CLIENT, "[HighlightContext] Pattern scan failed for ClientEnt_Highlight_SetCurrentContext -- entity overrides disabled\n");
		return;
	}
	if (!v_ClientEnt_Highlight_SetParam)
	{
		Warning(eDLL_T::CLIENT, "[HighlightContext] Pattern scan failed for ClientEnt_Highlight_SetParam -- entity overrides disabled\n");
		return;
	}
	if (!v_ClientEnt_Highlight_SetFunctions)
	{
		// Non-fatal: other overrides still function.
		Warning(eDLL_T::CLIENT, "[HighlightContext] Pattern scan failed for ClientEnt_Highlight_SetFunctions -- generic-context override disabled\n");
	}

	entityStruct->AddFunction(
		"Highlight_SetCurrentContext",
		"Script_Entity_Highlight_SetCurrentContext",
		"Sets highlight context with virtual ID remapping (SDK)",
		"void",
		"int contextId",
		false,
		Script_Entity_Highlight_SetCurrentContext);

	entityStruct->AddFunction(
		"Highlight_GetCurrentContext",
		"Script_Entity_Highlight_GetCurrentContext",
		"Gets highlight context with virtual ID reverse mapping (SDK)",
		"int",
		"",
		false,
		Script_Entity_Highlight_GetCurrentContext);

	entityStruct->AddFunction(
		"Highlight_SetParam",
		"Script_Entity_Highlight_SetParam",
		"Sets highlight param with virtual ID remapping (SDK)",
		"void",
		"int contextId, int paramIdx, vector value",
		false,
		Script_Entity_Highlight_SetParam);

	entityStruct->AddFunction(
		"Highlight_SetGenericHighlightContext",
		"Script_Entity_Highlight_SetGenericHighlightContext",
		"Bind a named context to a generic-type slot",
		"void",
		"int genericType, int contextId, bool isFocused",
		false,
		Script_Entity_Highlight_SetGenericHighlightContext);

	entityStruct->AddFunction(
		"Highlight_GetGenericHighlightContext",
		"Script_Entity_Highlight_GetGenericHighlightContext",
		"Read back the ctxId bound to a generic-type slot (SDK)",
		"int",
		"int genericType",
		false,
		Script_Entity_Highlight_GetGenericHighlightContext);

	entityStruct->AddFunction(
		"Highlight_OverrideParam",
		"Script_Entity_Highlight_OverrideParam",
		"Override a param on the entity's current active slot (SDK)",
		"void",
		"int paramIdx, vector value",
		false,
		Script_Entity_Highlight_OverrideParam);
}

// Interception is via AddFunction overrides, no C++ detours needed.

void HighlightContext_LevelShutdown()
{
	for (int i = 0; i < MAX_HIGHLIGHT_CONTEXTS; i++)
		s_contexts[i] = HighlightContextData_t();

	s_nameToId.clear();
	s_nextId = 0;
	s_s21IdsReady = false;
	s_entityActiveVirtualContext.Clear();
	s_entityGenericCtx.Clear();
}
#endif // CLIENT_DLL
