// Generated by tools/gen_mapeditor_catalog.py. Do not edit by hand.
#pragma once

struct MapEditPakAllowEntry_s
{
	const char* name;
	int bit;
};

static const MapEditPakAllowEntry_s s_MapEditPakAllowList[] =
{
	{ "mp_rr_angel_city", 1 },
	{ "mp_rr_arena_habitat", 2 },
	{ "mp_rr_arena_phase_runner", 3 },
	{ "mp_rr_boneyard", 4 },
	{ "mp_rr_canyonlands_hu", 5 },
	{ "mp_rr_canyonlands_staging_mu1", 6 },
	{ "mp_rr_crashsite", 7 },
	{ "mp_rr_desertlands_hu", 8 },
	{ "mp_rr_district", 9 },
	{ "mp_rr_divided_moon_mu1", 10 },
	{ "mp_rr_freedm_skulltown", 11 },
	{ "mp_rr_freedm_skulltown_s27", 12 },
	{ "mp_rr_olympus_mu2", 13 },
	{ "mp_rr_party_crasher", 14 },
	{ "mp_rr_thunderdome", 15 },
	{ "mp_rr_tropic_island_mu2", 16 },
};

static constexpr int kMapEditPakAllowCount = 16;
